# Generated by Django 3.0.7 on 2020-06-06 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truecaller', '0003_auto_20200606_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spam', models.ManyToManyField(to='truecaller.Spam')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usercontacts', models.ManyToManyField(to='truecaller.UserContacts')),
            ],
        ),
    ]
