# Generated by Django 3.0.7 on 2020-06-06 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truecaller', '0004_globaldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globaldata',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='globaldata',
            name='user_profile',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
